### ISSUE TITLE
Error when running cuda code

### ISSUE THREAD

**Issue by CheungBH** [creiser/kilonerf#29]
Thanks for your great work. I followed your instruction, but met some errors while importing kilonerf cuda:
Traceback (most recent call last):
  File "run_nerf.py", line 21, in <module>
    from run_nerf_helpers import *
  File "/vol/datastore/xxx/kilonerf/run_nerf_helpers.py", line 6, in <module>
    import kilonerf_cuda
ImportError: /media/sda1/xxx/anaconda3/envs/py3-mink/lib/python3.8/site-packages/kilonerf_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: MKL_Get_Version

But I successfully installed your cuda library with:
$ pip install $KILONERF_HOME/cuda/dist/kilonerf_cuda-0.0.0-cp38-cp38-linux_x86_64.whl
Processing ./cuda/dist/kilonerf_cuda-0.0.0-cp38-cp38-linux_x86_64.whl
kilonerf-cuda is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

Are there any suggestions?

**Comment by Ikarosy** [comment]
just `pip install mil`

**Comment by Ikarosy** [comment]
I encountered with the same issue. Just solve it by `conda install mkl` `conda install mkl-service`

**Comment by that-liu** [comment]
I have the same error ,solve by conda install mkl conda install mkl-service,But not feasible；Are there any suggestions?
My error:
ImportError: /home/xx/miniconda3/envs/pmpi/lib/python3.8/site-packages/kilonerf_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: MKL_Get_Version
Traceback (most recent call last):
  File "build_occupancy_tree.py", line 18, in <module>
    from utils import *
  File "/home/xxI/kilonerf/utils.py", line 9, in <module>
    import run_nerf_helpers
  File "/home/xx/kilonerf/run_nerf_helpers.py", line 6, in <module>
    import kilonerf_cuda
ImportError: /home/xx/miniconda3/envs/pmpi/lib/python3.8/site-packages/kilonerf_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: MKL_Get_Version
Traceback (most recent call last):
  File "local_distill.py", line 19, in <module>
    from utils import *
  File "/home/xx/MPI/kilonerf/utils.py", line 9, in <module>
    import run_nerf_helpers
  File "/home/xx/MPI/kilonerf/run_nerf_helpers.py", line 6, in <module>
    import kilonerf_cuda
ImportError: /home/xx/miniconda3/envs/pmpi/lib/python3.8/site-packages/kilonerf_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: MKL_Get_Version
Traceback (most recent call last):
  File "run_nerf.py", line 21, in <module>
    from run_nerf_helpers import *
  File "/home/xx/MPI/kilonerf/run_nerf_helpers.py", line 6, in <module>
    import kilonerf_cuda
ImportError: /home/xx/miniconda3/envs/pmpi/lib/python3.8/site-packages/kilonerf_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: MKL_Get_Version

**Comment by Ikarosy** [comment]
This error report has already clearly pointed out what was wrong: "undefined symbol: MKL_Get_Version". You can go ahead and solve it accordingly.

**Comment by SuperFCR** [comment]
Me too, can you provide any solutions?
